[project]
name = "zip-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"beautifulsoup4>=4.14.3",
	"dask[dataframe,distributed]>=2026.1.2",
]

[dependency-groups]
dev = [
    "mypy==1.19.1",
    "ruff==0.15.0",
]
